server:
  port: 9090


com:
  name: comname
  age: 888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vashdb
    username: root
    password: root


